# Generated by Django 3.2.10 on 2021-12-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Moje-posty'},
        ),
    ]
